#!/usr/bin/env python3
"""Generate docs/CATALOG.md — a legible inventory of every kit component.

Usage:
  python3 tests/gen-catalog.py           # write docs/CATALOG.md
  python3 tests/gen-catalog.py --check    # exit 1 if docs/CATALOG.md is stale

Parses frontmatter (name/description) from skills, agents, and commands; reads
hook wiring from hooks/hooks.json; lists rules. Deterministic so --check is a
stable CI freshness gate.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "CATALOG.md")
MAXLEN = 110


def frontmatter(path):
    """Return (name, description) from a markdown file's --- frontmatter block."""
    try:
        lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    except OSError:
        return "", ""
    if not lines or lines[0].strip() != "---":
        return "", ""
    name = desc = ""
    for ln in lines[1:]:
        if ln.strip() == "---":
            break
        if ln.startswith("name:"):
            name = ln.split(":", 1)[1].strip().strip("\"'")
        elif ln.startswith("description:"):
            desc = ln.split(":", 1)[1].strip().strip("\"'")
    return name, desc


def short(desc):
    desc = re.sub(r"\s+", " ", desc).strip()
    # First sentence if it's short enough, else hard truncate.
    first = re.split(r"(?<=[.!?])\s", desc, 1)[0]
    desc = first if first and len(first) <= MAXLEN else desc
    return (desc[: MAXLEN - 1] + "…") if len(desc) > MAXLEN else desc


def listdir(rel):
    p = os.path.join(ROOT, rel)
    return sorted(os.listdir(p)) if os.path.isdir(p) else []


def skills():
    rows = []
    for d in listdir("skills"):
        smd = os.path.join(ROOT, "skills", d, "SKILL.md")
        if os.path.isfile(smd):
            _, desc = frontmatter(smd)
            rows.append((d, short(desc)))
    return rows


def agents():
    rows = []
    for f in listdir("agents"):
        if f.endswith(".md"):
            name, desc = frontmatter(os.path.join(ROOT, "agents", f))
            rows.append((name or f[:-3], short(desc)))
    return rows


def commands():
    rows = []
    for f in listdir("commands"):
        if f.endswith(".md"):
            name, desc = frontmatter(os.path.join(ROOT, "commands", f))
            rows.append(("/" + (name or f[:-3]), short(desc)))
    return rows


def hooks():
    """event -> sorted list of referenced script basenames."""
    try:
        data = json.load(open(os.path.join(ROOT, "hooks", "hooks.json")))
    except OSError:
        return {}
    out = {}
    for event, groups in data.get("hooks", {}).items():
        scripts = set()
        for g in groups:
            for h in g.get("hooks", []):
                for m in re.findall(r"\$\{CLAUDE_PLUGIN_ROOT\}/(\S+?)(?:\"|\s|$)", h.get("command", "")):
                    scripts.add(os.path.basename(m))
        out[event] = sorted(scripts)
    return out


def rules():
    out = []
    base = os.path.join(ROOT, "rules")
    for dirpath, _, files in os.walk(base):
        for f in sorted(files):
            if f.endswith(".md"):
                out.append(os.path.relpath(os.path.join(dirpath, f), base))
    return sorted(out)


def render():
    sk, ag, cm, hk, rl = skills(), agents(), commands(), hooks(), rules()
    L = []
    L.append("# Catalog")
    L.append("")
    L.append("> Generated by `tests/gen-catalog.py` — do not edit by hand. "
             "Run `python3 tests/gen-catalog.py` to refresh; CI checks it is current.")
    L.append("")
    L.append(f"**{len(sk)} skills · {len(ag)} agents · {len(cm)} commands · "
             f"{len(hk)} hook events · {len(rl)} rule files**")
    L.append("")

    L.append(f"## Skills ({len(sk)})")
    L.append("")
    for name, desc in sk:
        L.append(f"- **{name}** — {desc}" if desc else f"- **{name}**")
    L.append("")

    L.append(f"## Agents ({len(ag)})")
    L.append("")
    for name, desc in ag:
        L.append(f"- **{name}** — {desc}" if desc else f"- **{name}**")
    L.append("")

    L.append(f"## Commands ({len(cm)})")
    L.append("")
    for name, desc in cm:
        L.append(f"- **{name}** — {desc}" if desc else f"- **{name}**")
    L.append("")

    L.append("## Hooks")
    L.append("")
    L.append("Active only when the kit is installed as a plugin (see `CLAUDE.md` → Activation).")
    L.append("")
    for event in sorted(hk):
        L.append(f"- **{event}**: {', '.join(hk[event]) or '—'}")
    L.append("")

    L.append(f"## Rules ({len(rl)})")
    L.append("")
    L.append("Referenced by skills/CLAUDE.md; not auto-loaded.")
    L.append("")
    for r in rl:
        L.append(f"- `{r}`")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    content = render()
    if "--check" in sys.argv[1:]:
        try:
            current = open(OUT, encoding="utf-8").read()
        except OSError:
            current = None
        if current != content:
            print("FAIL: docs/CATALOG.md is stale — run: python3 tests/gen-catalog.py", file=sys.stderr)
            return 1
        print("docs/CATALOG.md is up to date.")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(content)
    print(f"Wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
